const variables = {
  sizes: [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50,
    52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100,
  ] as const,
  sizeMultiplier: 0.25,
  colors: [
    'black',
    'white',
    'transparent',
    'primary',
    'primaryLight',
    'primaryDark',
    'secondary',
    'secondaryLight',
    'secondaryDark',
    'tertiary',
    'tertiaryLight',
    'tertiaryDark',
    'blue',
    'blueLight',
    'blueDark',
    'red',
    'redLight',
    'redDark',
    'purple',
    'purpleLight',
    'purpleDark',
    'yellow',
    'yellowLight',
    'yellowDark',
    'pink',
    'pinkLight',
    'pinkDark',
    'green',
    'greenLight',
    'greenDark',
    'orange',
    'orangeLight',
    'orangeDark',
    'navy',
    'navyLight',
    'navyDark',
    'teal',
    'tealLight',
    'tealDark',
    'violet',
    'violetLight',
    'violetDark',
    'gray',
    'grayLight',
    'grayDark',
    'brown',
    'brownLight',
    'brownDark',
    'orange',
    'orangeLight',
    'orangeDark',
  ] as const,
  fontColors: ['color1', 'color2', 'color3', 'color4', 'color5', 'color6', 'color7', 'color8', 'color9', 'color10'] as const,
  bgColors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const,
  borderColors: [1, 2, 3, 4, 5] as const,
  backgrounds: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const,
  shadows: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] as const,
  cursors: [
    'auto',
    'default',
    'none',
    'context-menu',
    'help',
    'pointer',
    'progress',
    'wait',
    'cell',
    'crosshair',
    'text',
    'vertical-text',
    'alias',
    'copy',
    'move',
    'no-drop',
    'not-allowed',
    'e-resize',
    'n-resize',
    'ne-resize',
    'nw-resize',
    's-resize',
    'se-resize',
    'sw-resize',
    'w-resize',
    'ew-resize',
    'ns-resize',
    'nesw-resize',
    'nwse-resize',
    'col-resize',
    'row-resize',
    'all-scroll',
    'zoom-in',
    'zoom-out',
    'grab',
    'grabbing',
  ] as const,
  fontSizes: [
    6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 54, 58, 64, 70, 78, 86, 96,
  ] as const,
};

export type SizeType = typeof variables.sizes[number];
export type ColorType = typeof variables.colors[number];
export type BaseFontColorType = typeof variables.fontColors[number];
export type BaseBgColorType = typeof variables.bgColors[number];
export type BaseBorderColorType = typeof variables.bgColors[number];
export type BackgroundType = typeof variables.backgrounds[number];
export type ShadowType = typeof variables.shadows[number];
export type CursorType = typeof variables.cursors[number];
export type FontSizeType = typeof variables.fontSizes[number];

export default variables;
