name: Tests
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies 🔧
        run: npm install
      - name: Check compiling 🔧
        run: npm run compiltypee
      - name: Check testing 🔧
        run: npm run test:all
